version: '3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE     : wordpress
            MYSQL_USER         : wordpress
            MYSQL_PASSWORD     : wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:5.7.2
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"
        environment:
            WORDPRESS_DB_HOST    : db:3306
            WORDPRESS_DB_USER    : wordpress
            WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db_data: